### ISSUE TITLE
Organization Dashboard

### ISSUE THREAD

**Issue by RafaelUngar** [rayshroom/InvenTurboFrontend#6]
Current progress is on the [1t4-org-dashboard branch](https://github.com/rayshroom/InvenTurboFrontend/tree/it4-org-dashboard) and looks like this:
![image](https://user-images.githubusercontent.com/13500769/69895538-ba503300-12ff-11ea-9e8f-b59af63f02b3.png)

### To-do:
*Replace hardcoding with calls to fetch functions:*
- [x] (1) `getCurrentOrganizationLink()` [on L26](https://github.com/rayshroom/InvenTurboFrontend/blob/it4-org-dashboard/src/app/components/views/organization-dashboard/organization-dashboard.component.ts#L26)
- [x] (2) `getCurrentOrganization()` [on L29](https://github.com/rayshroom/InvenTurboFrontend/blob/it4-org-dashboard/src/app/components/views/organization-dashboard/organization-dashboard.component.ts#L29)
- [x] (3) `getAllOrganizationTransactions(this.ol.oid)` [on L35](https://github.com/rayshroom/InvenTurboFrontend/blob/it4-org-dashboard/src/app/components/views/organization-dashboard/organization-dashboard.component.ts#L35)

*Add links to other components:*
- [x] Transaction list item links → Transaction Details ([It4 Task 1](https://github.com/SenecaCollegeBTSProjects/Group_17#to-do-3))
- [x] Create transaction button → Make Transaction Page ([It4 Task 1](https://github.com/SenecaCollegeBTSProjects/Group_17#to-do-3))
- [x] View inventory button → Inventory Page ([It4 Task 3](https://github.com/SenecaCollegeBTSProjects/Group_17#to-do-3))

*Nice-to-have improvements:*
- [ ] Implement tab functionality (Your Transactions 🡘 All Transactions)
- [ ] Improve responsiveness of transaction list items
- [ ] Adjust the styling of the circular photo icons to align them further with Victor's design
- [ ] Replace emojis (e.g. with Font Awesome characters) for cross-platform visual consistency
- [ ] Add link: View pending orders button → **???**
